### PR TITLE
Dockerfile for coffin container in alpine linux with only 22MB

### PR DESCRIPTION
**Pull request by ozbillwang**

### CODE REVIEW

**Comment by yyolk** [comment]
Since I actually don't have it on npm and @chrisfjones seems no responsive at this point... For low would you change this to be `npm -g yyolk/coffin`

It is docker after all

**Comment by yyolk** [comment]
Closing since you are a bot

**Comment by ozbillwang** [comment]
@yyolk 

What's the meaning of bot? Robot? Interesting why you have this idea. 

Anyway, I have updated the Dockerfile with your account in it. Did you see it?

If you don't like it, I will keep it in my fork, not bad idea.

**Comment by yyolk** [comment]
@SydOps sorry for the calling you a bot. i've been running into them lately.

Reopening this and will merge

**Pull request merged**
